databases:
  - name: djs-db
    databaseName: scheduler
    user: scheduler
    plan: free

services:

  # 1. FastAPI Backend
  - type: web
    name: djs-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djs-db
          property: connectionString

      - key: JWT_SECRET
        generateValue: true

      - key: JWT_ALGORITHM
        value: HS256

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"

      # Get frontend's public Render URL
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: djs-frontend
          envVarKey: RENDER_EXTERNAL_URL

      - key: WORKER_CONCURRENCY
        value: "4"

      - key: WORKER_POLL_INTERVAL_SECONDS
        value: "1"

      - key: HEARTBEAT_INTERVAL_SECONDS
        value: "5"

      - key: STALE_JOB_TIMEOUT_SECONDS
        value: "60"

    dockerCommand: >
      sh -c "alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port $PORT"


  # 2. React Frontend
  - type: web
    name: djs-frontend
    runtime: static
    plan: free

    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend

    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: djs-backend
          envVarKey: RENDER_EXTERNAL_URL


  # 3. Background Worker
  - type: worker
    name: djs-worker
    runtime: docker
    dockerfilePath: worker/Dockerfile
    plan: starter

    envVars:
      - key: API_BASE_URL
        fromService:
          type: web
          name: djs-backend
          envVarKey: RENDER_EXTERNAL_URL

      - key: WORKER_CONCURRENCY
        value: "4"

      - key: WORKER_POLL_INTERVAL_SECONDS
        value: "1"

      - key: HEARTBEAT_INTERVAL_SECONDS
        value: "5"
